from __future__ import annotations

from pathlib import Path
from typing import Optional, Protocol

from app.domain.pipelines.graph_pointer import GraphPointer
from app.domain.pipelines.pipeline_collection import PipelineCollection
from app.domain.pipelines.pipeline_unit import PipelineUnit


class PipelineMetadataRepository(Protocol):
    """Persistence port for pipeline metadata embedded in the project."""

    def load(self) -> PipelineCollection: ...
    def save(self, collection: PipelineCollection) -> None: ...


class GraphStoragePort(Protocol):
    """Filesystem operations for pipeline graph artifacts."""

    def set_project_context(
        self,
        project_root: Optional[Path],
        project_id: Optional[str] = None,
        project_meta_path: Optional[Path] = None,
    ) -> None: ...

    def draft_path_for(self, pipeline_name: str) -> Path: ...
    def final_path_for(self, pipeline_name: str) -> Path: ...
    def promote(self, pointer: GraphPointer) -> GraphPointer: ...
    def delete_graph(self, pointer: GraphPointer) -> None: ...
    def cleanup_shared_temp(self) -> None: ...
    def cleanup_current_shared_temp(self) -> None: ...
    def cleanup_project_orphans(self, expected_names: set[str]) -> None: ...


class PipelinePreviewPort(Protocol):
    """Handles preview asset persistence for pipelines."""

    def save_preview(self, pipeline: PipelineUnit, image_path: Path) -> Path: ...
    def delete_preview(self, pipeline: PipelineUnit) -> None: ...


class PipelinePreviewStore(Protocol):
    """Tracks transient preview image paths per pipeline (non-persistent)."""

    def get_preview(self, name: str) -> Optional[Path]: ...
    def set_preview(self, name: str, path: Optional[Path]) -> None: ...
    def clear(self, name: Optional[str] = None) -> None: ...


class ActivePipelineStore(Protocol):
    """Tracks the currently active pipeline without persisting it."""

    def get_active(self) -> Optional[str]: ...
    def set_active(self, name: Optional[str]) -> None: ...
    def clear(self) -> None: ...


class PyFlowGateway(Protocol):
    """UI-facing facade for manipulating the embedded PyFlow instance."""

    def load_graph(self, graph_path: Path) -> None: ...
    def save_graph(self, target_path: Path) -> None: ...
    def new_blank(self) -> None: ...
    def on_dirty_changed(self, callback: callable) -> None: ...
