from __future__ import annotations

from typing import Callable, Protocol


class PipelineListView(Protocol):
    """View contract for displaying and interacting with pipeline lists."""

    def set_items(self, names: list[str], active_name: str | None) -> None: ...
    def set_enabled(self, enabled: bool) -> None: ...

    def on_create_requested(self, callback: Callable[[], None]) -> None: ...
    def on_select_requested(self, callback: Callable[[str], None]) -> None: ...
    def on_delete_requested(self, callback: Callable[[str], None]) -> None: ...
