from __future__ import annotations

from typing import Callable, Protocol


class PipelinePropertiesView(Protocol):
    """View contract for editing a pipeline's properties."""

    def show_pipeline(self, name: str | None) -> None: ...
    def set_enabled(self, enabled: bool) -> None: ...

    def on_name_changed(self, callback: Callable[[str], None]) -> None: ...
    def on_save_requested(self, callback: Callable[[], None]) -> None: ...
    def on_discard_requested(self, callback: Callable[[], None]) -> None: ...
