from typing import Protocol, Optional


class MainWindowView(Protocol):
    def prompt_project_name(self) -> Optional[str]: ...

    def prompt_location_for_new_project(self) -> Optional[str]: ...

    def prompt_existing_project_location(self) -> Optional[str]: ...

    def update_window_title(self, title: str) -> None: ...
